baseurl: "/"
title: "Stackbit Fjord Theme"
page_load_js: "assets/js/main.js"
params:
  description: A minimal blogging theme for Stackbit
  header:
    title: Fjord
    tagline: Minimal and clean blog theme
    logo_img: "images/logo.png"
    background_img: "images/header-bg.jpg"
    has_nav: true
    nav_links:
      - label: Home
        url: /
      - label: About
        url: /about
      - label: Style Guide
        url: /style-guide
      - label: Contact
        url: /contact
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
      - label: Made with Stackbit.
        url: https://www.stackbit.com
        new_window: true
  palette: yellow
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
